"use strict";
exports.__esModule = true;
var express = require("express");
var shops = require("../../controllers/shop.controller");
var router = express.Router();
router.post("/", shops.create);
router.get("/", shops.findAll);
router.get("/:id", shops.findOne);
router.put("/:id", shops.update);
router["delete"]("/:id", shops["delete"]);
module.exports = router;
